#include<algorithm>
#include<iostream>
#include<array>
#include<cstring>
#include<string>
#include<ctime>
#include<cstdlib>
#include<fstream>

using namespace std;

int main(){
	srand(time(0));
	int x;
	ofstream fo;
	fo.open("mistakeTracker");
	int mistakes;
	int mistakes2;
	int mistakes3;
	int mistakes4;
	int mistakes5;
	int mistakes6;
	int mistakes7;
	int mistakes8;
	int mistakes9;
	int mistakes10;
	string solidOrBroken[] = {"solid", "broken"};
	string majMinScales[] = {"C major", "C harmonic minor", "C melodic minor", "D major", "D harmonic minor", "D melodic minor", "F major", "F harmonic minor", "F melodic minor", "Ab major", "G# harmonic minor", "G# melodic minor", "Gb major", "F# harmonic minor", "F# melodic minor"};
	string chromScales[] = {"Starting on D", "Starting on Ab"};
	string formulaPatterns[] = {"D major", "D harmonic minor"};
	string fourNoteChords[] = {"C major", "C minor", "D major", "D minor", "F major", "F minor", "Ab major", "G# minor", "Gb major", "F# minor"};
	string dominantSeventhChords[] = {"G7", "A7", "C7", "Eb7", "Db7"};
	string diminishedSeventhChords[] = {"B dim 7", "C# dim 7", "E dim 7", "G dim 7", "F dim 7"};
	system("clear");
	cout << "MAJOR / MINOR SCALES: \n";
	cout << majMinScales[rand()%15] << endl;
	cout << "Mistakes: ";
	cin >> mistakes;
	system("clear");
	cout << majMinScales[rand()%15] << endl;
	cout << "Mistakes: ";
	cin >> x;
	mistakes += x;
	system("clear");
	cout << majMinScales[rand()%15] << endl;
	cout << "Mistakes: ";
	cin >> x;
	mistakes += x;
	system("clear");
	cout << "CHROMATIC SCALES: \n";
	cout << chromScales[rand()%2] << endl;
	cout << "Mistakes: ";
	cin >> mistakes2;
	system("clear");
	cout << "FORMULA PATTERN SCALES: \n";
	cout << formulaPatterns[rand()%2] << endl;
	cout << "Mistakes: ";
	cin >> mistakes3;
	system("clear");
	cout << "FOUR NOTE CHORDS: \n";
	cout << fourNoteChords[rand()%10] << endl;
	cout << "Mistakes: ";
	cin >> mistakes4;
	system("clear");
	cout << fourNoteChords[rand()%10] << endl;
	cout << "Mistakes: ";
	cin >> x;
	mistakes4 += x;
	system("clear");
	cout << "DOMINANT SEVENTH CHORDS: \n";
	cout << dominantSeventhChords[rand()%5] << " " << solidOrBroken[rand()%2] << endl;
	cout << "Mistakes: ";
	cin >> mistakes5;
	system("clear");
	cout << dominantSeventhChords[rand()%5] << " " << solidOrBroken[rand()%2] << endl;
	cout << "Mistakes: ";
	cin >> x;
	mistakes5 += x;
	system("clear");
	cout << "DIMISHED SEVENTH CHORDS: \n";
	cout << diminishedSeventhChords[rand()%5] << " " << solidOrBroken[rand()%2] << endl;
	cout << "Mistakes: ";
	cin >> mistakes6;
	system("clear");
	cout << diminishedSeventhChords[rand()%5] << " " << solidOrBroken[rand()%2] << endl;
	cout << "Mistakes: ";
	cin >> x;
	mistakes6 += x;
	system("clear");
	cout << "TONIC ARPEGGIOS:\n";
	cout << fourNoteChords[rand()%10] << endl;
	cout << "Mistakes: ";
	cin >> mistakes7;
	system("clear");
	cout << fourNoteChords[rand()%10] << endl;
	cout << "Mistakes: ";
	cin >> x;
	mistakes7 += x;
	system("clear");
	cout << "DOMINANT SEVENTH ARPEGGIOS:\n";
	cout << dominantSeventhChords[rand()%5] << endl;
	cout << "Mistakes: ";
	cin >> mistakes8;
	system("clear");
	cout << "DIMINISHED SEVENTH ARPEGGIOS:\n";
	cout << diminishedSeventhChords[rand()%5] << endl;
	cout << "Mistakes: ";
	cin >> mistakes9;
	system("clear");
	cout << "SONGS:\n";
	cout << "Etude in D Minor\n";
	cout << "Mistakes: ";
	cin >> mistakes10;
	system("clear");
	cout << "Etude in G Major\n";
	cout << "Mistakes: ";
	cin >> x;
	mistakes10 += x;
	system("clear");
	cout << "Bourr\u00E9e in F Major\n";
	cout << "Mistakes: ";
	cin >> x;
	mistakes10 += x;
	system("clear");
	cout << "Fur Elise\n";
	cout << "Mistakes: ";
	cin >> x;
	mistakes10 += x;
	system("clear");
	cout << "Rock Zone\n";
	cout << "Mistakes: ";
	cin >> x;
	mistakes10 += x;
	system("clear");
	cout << "Fantaisie Impromptu\n";
	cout << "Mistakes: ";
	cin >> x;
	mistakes10 += x;
	fo << "Major/minor scales " << to_string(mistakes) << endl;
	fo << "Chromatic scales " << to_string(mistakes2) << endl;
	fo << "Formula pattern scales " << to_string(mistakes3) << endl;
	fo << "Four note chords " << to_string(mistakes4) << endl;
	fo << "Dominant 7th chords " << to_string(mistakes5) << endl;
	fo << "Diminished 7th chords " << to_string(mistakes6) << endl;
	fo << "Tonic arpeggios " << to_string(mistakes7) << endl;
	fo << "Dominant 7th arpeggios " << to_string(mistakes8) << endl;
	fo << "Diminished 7th arpeggios " << to_string(mistakes9) << endl;
	fo << "Songs " << to_string(mistakes10) << endl;
	
}
