#include<iostream>
#include<cstdlib>
#include<ctime>

using namespace std;
int main(){
	srand(time(NULL));
	string items[] = {"G major scale", "G harmonic minor scale", "G melodic minor scale", "E major scale", "E harmonic minor scale", "E melodic minor scale", "B major scale", "B harmonic minor scale", "B melodic minor scale", "Db major scale", "C# harmonic minor scale", "C# melodic minor scale", "E major formula pattern scale", "E harmonic minor formula pattern scale", "G major triad", "G minor triad", "E major triad", "E minor triad", "B major triad", "B minor triad", "Db major triad", "C# minor triad", "D7 chord broken for right hand", "D7 chord solid for right hand", "D7 chord broken for left hand", "D7 chord solid for left hand", "B7 chord broken for right hand", "B7 chord solid for right hand", "B7 chord broken for left hand", "B7 chord solid for left hand", "F#7 chord broken for right hand", "F#7 chord solid for right hand", "F#7 chord broken for left hand", "F#7 chord solid for left hand", "Ab7 chord broken for right hand", "Ab7 chord solid for right hand", "Ab7 chord broken for left hand", "Ab7 chord solid for left hand", "F#dim7 chord broken for right hand", "F#dim7 chord solid for right hand", "F#dim7 chord broken for left hand", "F#dim7 chord solid for left hand", "Ebdim7 chord broken for right hand", "Ebdim7 chord solid for right hand", "Ebdim7 chord broken for left hand", "Ebdim7 chord solid for left hand", "Bbdim7 chord broken for right hand", "Bbdim7 chord solid for right hand", "Bbdim7 chord broken for left hand", "Bbdim7 chord solid for left hand", "Cdim7 chord broken for right hand", "Cdim7 chord solid for right hand", "Cdim7 chord broken for left hand", "Cdim7 chord solid for left hand", "G major arpeggio for right hand", "G major arpeggio for left hand", "G minor arpeggio for right hand", "G minor arpeggio for left hand", "E major arpeggio for right hand", "E major arpeggio for left hand", "E minor arpeggio for right hand", "E minor arpeggio for left hand", "B major arpeggio for right hand", "B major arpeggio for left hand", "B minor arpeggio for right hand", "B minor arpeggio for left hand", "Db major arpeggio for right hand", "Db major arpeggio for left hand", "C# minor arpeggio for right hand", "C# minor arpeggio for left hand", "D7 arpeggio for right hand", "D7 arpeggio for left hand", "B7 arpeggio for right hand", "B7 arpeggio for left hand", "F#7 arpeggio for right hand", "F#7 arpeggio for left hand", "Ab7 arpeggio for right hand", "Ab7 arpeggio for left hand", "F#dim7 arpeggio for right hand", "F#dim7 arpeggio for left hand", "Ebdim7 arpeggio for right hand", "Ebdim7 arpeggio for left hand", "Bbdim7 arpeggio for right hand", "Bbdim7 arpeggio for left hand", "Cdim7 arpeggio for right hand", "Cdim7 arpeggio for left hand", "Toccatina", "Etude in Ab major", "Little prelude in E minor", "Rondo in C major", "Happy time Jazz"};
	cout << items[rand()%91] << endl;
}
